name: project_template
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  get_it: ^7.2.0
  useful_extensions: ^0.0.1
  json_annotation: ^4.5.0
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.2.1
  injectable: ^1.5.3
  responsive_framework: ^0.2.0
  freezed_annotation: ^2.0.3
  rxdart: ^0.27.4
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  async_redux: ^15.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  injectable_generator: ^1.5.3
  dart_code_metrics: ^4.16.0
  retrofit_generator: ^4.0.1
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
