name: project_template
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.0.3
  flutter_bloc: ^8.1.1

  # Network
  dio: ^5.4.2+1

  # Storage
  shared_preferences: ^2.0.15

  # Localization
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

  # Navigation
  auto_route: ^8.1.0

  # Tools
  json_annotation: ^4.6.0
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.2.0

  # Utils
  flutter_dotenv: ^5.1.0
  logger: ^2.2.0

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  equatable: ^2.0.5

  # Dependency Injection
  injectable: ^2.4.1
  get_it: ^7.7.0

  # UI
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  animate_gradient: ^0.0.2+1
  sheet: ^1.0.0
  lottie: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - .env
